# Generated by Django 3.2.5 on 2021-07-09 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_type', models.CharField(choices=[('short-term', 'Short Term (Kootah Modat)'), ('long-term', 'Long Term (Boland Modat)'), ('current', 'Current (Jari)'), ('gharz', 'Gharz ol Hasane')], default='short-term', max_length=100, verbose_name='Account Type')),
                ('conf_label', models.CharField(choices=[('top-secret', 'Top Secret'), ('secret', 'Secret'), ('confidential', 'Confidential'), ('unclassified', 'Unclassified')], default='unclassified', max_length=100, verbose_name='Confidentiality Label')),
                ('integrity_label', models.CharField(choices=[('very-trusted', 'Very Trusted'), ('trusted', 'Trusted'), ('slightly-trusted', 'Slightly Trusted'), ('untrusted', 'Untrusted')], default='untrusted', max_length=100, verbose_name='Integrity Label')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
    ]
