# Generated by Django 3.2.5 on 2021-07-09 14:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.CharField(default=uuid.uuid1, editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
