# Generated by Django 3.2.5 on 2021-07-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.CharField(default=3053681618, editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
