# Generated by Django 3.2.5 on 2021-07-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210709_1600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaljoinedrequest',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Joined Request'},
        ),
        migrations.AlterModelOptions(
            name='joinedrequest',
            options={'verbose_name': 'Joined Request', 'verbose_name_plural': 'Joined Requests'},
        ),
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.CharField(default=2787380458, editable=False, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='id',
            field=models.CharField(db_index=True, default=2787380458, editable=False, max_length=10),
        ),
    ]
