# Generated by Django 3.2.5 on 2021-07-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210709_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.CharField(default=2842121168, editable=False, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='id',
            field=models.CharField(db_index=True, default=2842121168, editable=False, max_length=10),
        ),
    ]
