# Generated by Django 3.2.5 on 2021-07-09 17:01

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210709_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.CharField(default=accounts.models.get_new_id, editable=False, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='id',
            field=models.CharField(db_index=True, default=accounts.models.get_new_id, editable=False, max_length=10),
        ),
    ]
