# Generated by Django 3.2.5 on 2021-07-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210709_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaljoinedrequest',
            name='conf_label',
            field=models.SmallIntegerField(choices=[(4, 'Top Secret'), (3, 'Secret'), (2, 'Confidential'), (1, 'Unclassified')], default=1, verbose_name='Confidentiality Label'),
        ),
        migrations.AlterField(
            model_name='historicaljoinedrequest',
            name='integrity_label',
            field=models.SmallIntegerField(choices=[(4, 'Very Trusted'), (3, 'Trusted'), (2, 'Slightly Trusted'), (1, 'Untrusted')], default=1, verbose_name='Integrity Label'),
        ),
        migrations.AlterField(
            model_name='joinedrequest',
            name='conf_label',
            field=models.SmallIntegerField(choices=[(4, 'Top Secret'), (3, 'Secret'), (2, 'Confidential'), (1, 'Unclassified')], default=1, verbose_name='Confidentiality Label'),
        ),
        migrations.AlterField(
            model_name='joinedrequest',
            name='integrity_label',
            field=models.SmallIntegerField(choices=[(4, 'Very Trusted'), (3, 'Trusted'), (2, 'Slightly Trusted'), (1, 'Untrusted')], default=1, verbose_name='Integrity Label'),
        ),
    ]
