# Generated by Django 3.2.5 on 2021-07-09 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210709_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaljoinedrequest',
            name='requested_account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.account', verbose_name='Requested Account'),
        ),
        migrations.AlterField(
            model_name='joinedrequest',
            name='requested_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined_requests', to='accounts.account', verbose_name='Requested Account'),
        ),
    ]
