# Generated by Django 3.2.5 on 2021-07-09 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20210709_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaljoinedrequest',
            name='conf_label',
            field=models.SmallIntegerField(choices=[(4, 'Top Secret'), (3, 'Secret'), (2, 'Confidential'), (1, 'Unclassified')], default=1, verbose_name='Requested Confidentiality Label'),
        ),
        migrations.AlterField(
            model_name='historicaljoinedrequest',
            name='integrity_label',
            field=models.SmallIntegerField(choices=[(4, 'Very Trusted'), (3, 'Trusted'), (2, 'Slightly Trusted'), (1, 'Untrusted')], default=1, verbose_name='Requested Integrity Label'),
        ),
        migrations.AlterField(
            model_name='historicaljoinedrequest',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Applicant User'),
        ),
        migrations.AlterField(
            model_name='joinedrequest',
            name='conf_label',
            field=models.SmallIntegerField(choices=[(4, 'Top Secret'), (3, 'Secret'), (2, 'Confidential'), (1, 'Unclassified')], default=1, verbose_name='Requested Confidentiality Label'),
        ),
        migrations.AlterField(
            model_name='joinedrequest',
            name='integrity_label',
            field=models.SmallIntegerField(choices=[(4, 'Very Trusted'), (3, 'Trusted'), (2, 'Slightly Trusted'), (1, 'Untrusted')], default=1, verbose_name='Requested Integrity Label'),
        ),
        migrations.AlterField(
            model_name='joinedrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined_requests', to=settings.AUTH_USER_MODEL, verbose_name='Applicant User'),
        ),
    ]
