# Generated by Django 3.2.5 on 2021-07-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='browser',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Browser'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='content_type',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Content-Type'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='log_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Log Name'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='method',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Method'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Path'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='remote_address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Remote Address'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user_agent',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='User Agent'),
        ),
    ]
